alias ..='cd ..'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias du='du -kh'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias jslint='~/.npm/jslint/0.11.0/package/bin/jslint.js'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias projects='cd ~/projects'
alias proxyoff='export http_proxy='\'''\'';export https_proxy='\'''\'''
alias proxyon='export http_proxy='\''http://localhost:3128'\'';export https_proxy='\''https://localhost:3128'\'''
alias ssh-acessos='ssh xbdia35@acessos'
alias ssh-repos='ssh xbdia35@repos'
alias gti='git'
